# Generated by Django 3.0.7 on 2020-06-22 22:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField()),
                ('numbers_drawn', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jackpot_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('jackpot_won', models.BooleanField(blank=True, null=True)),
                ('num_tickets_purchased', models.PositiveIntegerField(blank=True, null=True)),
                ('winners_categories', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='games.Game')),
            ],
        ),
    ]
