# Generated by Django 3.0.7 on 2020-06-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0004_auto_20200623_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='jackpot_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
