# Generated by Django 3.0.7 on 2020-06-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0005_auto_20200625_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='jackpot_amount',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
