# Generated by Django 3.0.7 on 2020-06-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0006_auto_20200626_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='predicted_num_tickets_purchased',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draw',
            name='predicted_yield',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
