# Generated by Django 3.0.7 on 2020-06-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0007_auto_20200626_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='predicted_jackpot_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
