# Generated by Django 3.0.7 on 2020-06-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0009_remove_draw_winners_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='winners_categories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
